version: '3'

services: 
    app:
        build: ./app
        container_name: 'app'
        volumes: 
            - ./app:/usr/src/
        tty: true
        stdin_open: true
        ports:
            - "8080:8080"
        command: sh -c  "cd app && yarn install && yarn serve"

    api:    
        build: ./api
        container_name: 'api'
        volumes:
            - ./app:/python/src
        ports:
            - "5000:5000"


    web_server:
        build: ./web_server
        container_name: 'web_server'
        tty: true
        stdin_open: true
        volumes:
            - ./web_server/html/source:/usr/share/nginx/html
            - ./web_server/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - "8000:80"  
