version: '3'

services: 
    app:
        build: ./app
        container_name: 'app'

    api:    
        build: ./api
        container_name: 'api'
        volumes:
            - ./app:/python/src
        ports:
            - "5000:5000"
